[tool.black]
line-length = 120
include = '\.pyi?$'
target-version = [
    "py39",
    "py310",
    "py311",
    "py312",
]
exclude = '''
/(
  \.git
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
default_section = "THIRDPARTY"
known_first_party = "pimdb,tests"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-rA"
]
testpaths = [
    "tests",
]

[pycodestyle]
max-line-length = 120
